version: "2.1"
services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - PATH-TO-REPO/deluge-compose/deluge-config/:/config
      - PATH-TO-DOWNLOADS-FOLDER/:/downloads
    restart: unless-stopped

